# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68a82204c31b070f91c83d5c38970cca5af62e858431dac1bb9c5e06a3a05f37d8cf2cbf8cc75cf3db9826f4bb6436305e69b3ac8a283a453a6ee3bc39e802ae

test:
  secret_key_base: e78764045cacb921b76554af42d256011ce61af4586ba8cfbbf899fe3496dd2b2beafd5215e3996811bd949f9ba61518664514667d760d5037febb83b6dafd15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
